create table if not exists public.report_master (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_name text not null,
  report_title text null,
  report_type text not null check (report_type in ('mis', 'transaction_print')),
  engine text not null default 'jasper' check (engine in ('jasper')),
  jasper_report_name text null,
  jasper_file_name text null,
  jasper_path text null,
  data_source_key text null,
  query_template text null,
  procedure_name text null,
  description text null,
  help_doc_url text null,
  param_schema jsonb not null default '[]'::jsonb,
  ui_schema jsonb not null default '{}'::jsonb,
  export_options jsonb not null default '{"pdf": true, "xlsx": false, "csv": false}'::jsonb,
  scope_rules jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  version integer not null default 1,
  created_by uuid null,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_report_master_type_active
  on public.report_master (report_type, is_active, report_name);

create table if not exists public.report_run_log (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.report_master(id) on delete cascade,
  report_key text not null,
  report_type text not null,
  requested_format text not null check (requested_format in ('pdf', 'xlsx', 'csv')),
  run_mode text not null default 'sync' check (run_mode in ('sync', 'async')),
  status text not null check (status in ('queued', 'running', 'success', 'failed')),
  actor_user_id uuid null,
  actor_role text null,
  source_page text null,
  request_params jsonb not null default '{}'::jsonb,
  normalized_params jsonb not null default '{}'::jsonb,
  output_meta jsonb not null default '{}'::jsonb,
  error_message text null,
  started_at timestamptz null,
  finished_at timestamptz null,
  duration_ms integer null,
  created_at timestamptz not null default now()
);

create index if not exists idx_report_run_log_report_created
  on public.report_run_log (report_id, created_at desc);

create index if not exists idx_report_run_log_status_created
  on public.report_run_log (status, created_at desc);
