insert into public.report_master (
  report_key,
  report_name,
  report_title,
  report_type,
  engine,
  jasper_report_name,
  jasper_file_name,
  jasper_path,
  data_source_key,
  query_template,
  procedure_name,
  description,
  param_schema,
  export_options,
  scope_rules,
  is_active,
  version
)
values
  (
    'mis_booking_value_daily_summary',
    'Booking Value Daily Summary',
    'Daily Booking Value Summary',
    'mis',
    'jasper',
    'MisBookingValueDailySummary',
    'mis_booking_value_daily_summary.jasper',
    '/reports/mis/mis_booking_value_daily_summary.jasper',
    'labbit_primary',
    'select date(created_at) as booked_date, count(*) as bookings, sum(coalesce((request_payload_json->>''total'')::numeric,0)) as gross_amount from quickbookings where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1 order by 1;',
    'sp_mis_booking_value_daily_summary',
    'Daily booked value proxy from quickbookings payload totals (not finalized revenue).',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_booking_value_monthly_summary',
    'Booking Value Monthly Summary',
    'Monthly Booking Value Summary',
    'mis',
    'jasper',
    'MisBookingValueMonthlySummary',
    'mis_booking_value_monthly_summary.jasper',
    '/reports/mis/mis_booking_value_monthly_summary.jasper',
    'labbit_primary',
    'select to_char(created_at,''YYYY-MM'') as month_key, count(*) as bookings, sum(coalesce((request_payload_json->>''total'')::numeric,0)) as gross_amount from quickbookings where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1 order by 1;',
    'sp_mis_booking_value_monthly_summary',
    'Monthly booked value proxy from quickbookings payload totals (not finalized revenue).',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_tat_visit_lifecycle',
    'Visit TAT Lifecycle',
    'Visit Turnaround Time',
    'mis',
    'jasper',
    'MisTatVisitLifecycle',
    'mis_tat_visit_lifecycle.jasper',
    '/reports/mis/mis_tat_visit_lifecycle.jasper',
    'labbit_primary',
    'select v.id as visit_id, v.visit_date, v.status, e.name as executive_name from visits v left join executives e on e.id = v.executive_id where v.lab_id = :lab_id and v.visit_date between :from_date and :to_date;',
    'sp_mis_tat_visit_lifecycle',
    'Lifecycle TAT report based on visits and visit activity logs.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"},{"key":"executive_id","label":"Phlebo","type":"uuid","required":false,"control":"select"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_visits_per_phlebo_monthly',
    'Visits Per Phlebo Monthly',
    'Phlebo Productivity Monthly',
    'mis',
    'jasper',
    'MisVisitsPerPhleboMonthly',
    'mis_visits_per_phlebo_monthly.jasper',
    '/reports/mis/mis_visits_per_phlebo_monthly.jasper',
    'labbit_primary',
    'select to_char(v.visit_date::date,''YYYY-MM'') as month_key, e.name as executive_name, count(*) as total_visits, count(*) filter (where lower(coalesce(v.status,'''')) = ''completed'') as completed_visits from visits v left join executives e on e.id = v.executive_id where v.lab_id = :lab_id and v.visit_date between :from_date and :to_date group by 1,2 order by 1,2;',
    'sp_mis_visits_per_phlebo_monthly',
    'Monthly visit and completion counts per phlebo.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_visit_status_funnel',
    'Visit Status Funnel',
    'Visit Status Funnel',
    'mis',
    'jasper',
    'MisVisitStatusFunnel',
    'mis_visit_status_funnel.jasper',
    '/reports/mis/mis_visit_status_funnel.jasper',
    'labbit_primary',
    'select lower(coalesce(status,''unassigned'')) as status_code, count(*) as visits from visits where lab_id = :lab_id and visit_date between :from_date and :to_date group by 1 order by 2 desc;',
    'sp_mis_visit_status_funnel',
    'Status funnel for operational review.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_quickbooking_conversion',
    'Quickbooking Conversion',
    'Quickbooking Conversion Report',
    'mis',
    'jasper',
    'MisQuickbookingConversion',
    'mis_quickbooking_conversion.jasper',
    '/reports/mis/mis_quickbooking_conversion.jasper',
    'labbit_primary',
    'select lower(coalesce(status,''pending'')) as booking_status, count(*) as bookings from quickbookings where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1 order by 2 desc;',
    'sp_mis_quickbooking_conversion',
    'Pending, booked, rejected, and closed quickbooking split.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_quickbooking_followup_tracker',
    'Quickbooking Follow-up Tracker',
    'Quickbooking Follow-up Tracker',
    'mis',
    'jasper',
    'MisQuickbookingFollowupTracker',
    'mis_quickbooking_followup_tracker.jasper',
    '/reports/mis/mis_quickbooking_followup_tracker.jasper',
    'labbit_primary',
    'select id, patient_name, phone, status, followup_status, followup_outcome, next_followup_at from quickbookings where lab_id = :lab_id and date(created_at) between :from_date and :to_date order by next_followup_at nulls last;',
    'sp_mis_quickbooking_followup_tracker',
    'Follow-up status tracker for call-center and booking desk.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"},{"key":"followup_status","label":"Follow-up Status","type":"text","required":false,"control":"select"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_sample_pickup_tat',
    'Sample Pickup TAT',
    'Sample Pickup TAT',
    'mis',
    'jasper',
    'MisSamplePickupTat',
    'mis_sample_pickup_tat.jasper',
    '/reports/mis/mis_sample_pickup_tat.jasper',
    'labbit_primary',
    'select sp.id, sp.status, sp.created_at, sp.picked_up_at, sp.dropped_off_at, cc.name as centre_name from sample_pickups sp left join collection_centre cc on cc.id = sp.collection_centre_id where sp.lab_id = :lab_id and date(sp.created_at) between :from_date and :to_date;',
    'sp_mis_sample_pickup_tat',
    'Pickup-to-drop turnaround by center and date window.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_sample_pickup_pending_ageing',
    'Sample Pickup Pending Ageing',
    'Sample Pickup Pending Ageing',
    'mis',
    'jasper',
    'MisSamplePickupPendingAgeing',
    'mis_sample_pickup_pending_ageing.jasper',
    '/reports/mis/mis_sample_pickup_pending_ageing.jasper',
    'labbit_primary',
    'select sp.id, sp.status, sp.created_at, cc.name as centre_name from sample_pickups sp left join collection_centre cc on cc.id = sp.collection_centre_id where sp.lab_id = :lab_id and sp.status in (''samples_ready'',''picked_up'') order by sp.created_at asc;',
    'sp_mis_sample_pickup_pending_ageing',
    'Pending pickups with ageing buckets.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_report_dispatch_performance',
    'Report Dispatch Performance',
    'Report Dispatch Performance',
    'mis',
    'jasper',
    'MisReportDispatchPerformance',
    'mis_report_dispatch_performance.jasper',
    '/reports/mis/mis_report_dispatch_performance.jasper',
    'labbit_primary',
    'select date(created_at) as run_date, status, count(*) as attempts from report_dispatch_logs where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1,2 order by 1,2;',
    'sp_mis_report_dispatch_performance',
    'Dispatch success/failure counts by day.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_report_dispatch_pending_print_once',
    'Pending Print-Once Review',
    'Pending Print-Once Review',
    'mis',
    'jasper',
    'MisPendingPrintOnceReview',
    'mis_report_dispatch_pending_print_once.jasper',
    '/reports/mis/mis_report_dispatch_pending_print_once.jasper',
    'labbit_primary',
    'select reqno, reqid, patient_phone, pending_ready_keys, created_at from report_dispatch_logs where lab_id = :lab_id and status = ''pending'' order by created_at desc;',
    'sp_mis_report_dispatch_pending_print_once',
    'Pending print-once exceptions for kiosk and admin follow-up.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_audit_log_review',
    'Audit Log Review',
    'Audit Log Review',
    'mis',
    'jasper',
    'MisAuditLogReview',
    'mis_audit_log_review.jasper',
    '/reports/mis/mis_audit_log_review.jasper',
    'labbit_primary',
    'select created_at, actor_name, actor_role, action, entity_type, entity_id, status, metadata_json from audit_logs where coalesce(lab_id::text,:lab_id::text) = :lab_id::text and date(created_at) between :from_date and :to_date order by created_at desc;',
    'sp_mis_audit_log_review',
    'Cross-endpoint API change review based on audit_logs.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"},{"key":"action","label":"Action","type":"text","required":false,"control":"text"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_uac_permissions_matrix',
    'UAC Permission Matrix',
    'UAC Permission Matrix',
    'mis',
    'jasper',
    'MisUacPermissionsMatrix',
    'mis_uac_permissions_matrix.jasper',
    '/reports/mis/mis_uac_permissions_matrix.jasper',
    'labbit_primary',
    'select role_key, permission_key, is_allowed, lab_id from uac_role_permissions where lab_id = :lab_id order by role_key, permission_key;',
    'sp_mis_uac_permissions_matrix',
    'Role-permission map for access governance.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_whatsapp_operations',
    'WhatsApp Operations Summary',
    'WhatsApp Operations Summary',
    'mis',
    'jasper',
    'MisWhatsappOperationsSummary',
    'mis_whatsapp_operations.jasper',
    '/reports/mis/mis_whatsapp_operations.jasper',
    'labbit_primary',
    'select date(created_at) as log_date, direction, count(*) as messages from whatsapp_messages where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1,2 order by 1;',
    'sp_mis_whatsapp_operations',
    'Inbound/outbound operational trends for WhatsApp desk.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_campaign_performance',
    'Campaign Performance',
    'Campaign Performance',
    'mis',
    'jasper',
    'MisCampaignPerformance',
    'mis_campaign_performance.jasper',
    '/reports/mis/mis_campaign_performance.jasper',
    'labbit_primary',
    'select c.name as campaign_name, c.status as campaign_status, count(cr.id) as recipients, count(*) filter (where lower(coalesce(cr.status,''''))=''sent'') as sent_count, count(*) filter (where lower(coalesce(cr.status,''''))=''failed'') as failed_count from campaigns c left join campaign_recipients cr on cr.campaign_id = c.id where c.lab_id = :lab_id and date(c.created_at) between :from_date and :to_date group by 1,2 order by c.name;',
    'sp_mis_campaign_performance',
    'Campaign recipient and delivery outcomes.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_collection_centre_productivity',
    'Collection Centre Productivity',
    'Collection Centre Productivity',
    'mis',
    'jasper',
    'MisCollectionCentreProductivity',
    'mis_collection_centre_productivity.jasper',
    '/reports/mis/mis_collection_centre_productivity.jasper',
    'labbit_primary',
    'select cc.name as centre_name, count(sp.id) as pickups, count(*) filter (where lower(coalesce(sp.status,''''))=''dropped'') as dropped_count from collection_centre cc left join sample_pickups sp on sp.collection_centre_id = cc.id where cc.lab_id = :lab_id and date(coalesce(sp.created_at, now())) between :from_date and :to_date group by 1 order by 2 desc;',
    'sp_mis_collection_centre_productivity',
    'Center-wise pickup and completion report.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'mis_cto_service_health',
    'CTO Service Health',
    'CTO Service Health',
    'mis',
    'jasper',
    'MisCtoServiceHealth',
    'mis_cto_service_health.jasper',
    '/reports/mis/mis_cto_service_health.jasper',
    'labbit_primary',
    'select service_name, count(*) as log_rows, max(created_at) as last_event_at from cto_service_logs where lab_id = :lab_id and date(created_at) between :from_date and :to_date group by 1 order by 1;',
    'sp_mis_cto_service_health',
    'System health and incident trends from CTO logs.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":true,"csv":true}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_patient_master_print',
    'Patient Master Print',
    'Patient Master',
    'transaction_print',
    'jasper',
    'TxnPatientMasterPrint',
    'txn_patient_master_print.jasper',
    '/reports/transaction/txn_patient_master_print.jasper',
    'labbit_primary',
    'select p.*, pa.area, pa.address_line, pa.lat, pa.lng from patients p left join patient_addresses pa on pa.patient_id = p.id and pa.is_default = true where p.id = :patient_id;',
    'sp_txn_patient_master_print',
    'Patient demographic and default address print.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"patient_id","label":"Patient","type":"uuid","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_visit_details_print',
    'Visit Details Print',
    'Visit Details',
    'transaction_print',
    'jasper',
    'TxnVisitDetailsPrint',
    'txn_visit_details_print.jasper',
    '/reports/transaction/txn_visit_details_print.jasper',
    'labbit_primary',
    'select v.*, p.name as patient_name, p.phone as patient_phone, e.name as executive_name, ts.slot_name from visits v left join patients p on p.id = v.patient_id left join executives e on e.id = v.executive_id left join visit_time_slots ts on ts.id = v.time_slot where v.id = :visit_id and v.lab_id = :lab_id;',
    'sp_txn_visit_details_print',
    'Single visit printable sheet for patient/ops handover.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"visit_id","label":"Visit","type":"uuid","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_visit_activity_print',
    'Visit Activity Print',
    'Visit Activity Timeline',
    'transaction_print',
    'jasper',
    'TxnVisitActivityPrint',
    'txn_visit_activity_print.jasper',
    '/reports/transaction/txn_visit_activity_print.jasper',
    'labbit_primary',
    'select * from visit_activity_log where visit_id = :visit_id order by created_at desc;',
    'sp_txn_visit_activity_print',
    'Chronological visit activity timeline print.',
    '[{"key":"visit_id","label":"Visit","type":"uuid","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":false}'::jsonb,
    true,
    1
  ),
  (
    'txn_quickbooking_request_print',
    'Quickbooking Request Print',
    'Booking Request Slip',
    'transaction_print',
    'jasper',
    'TxnQuickbookingRequestPrint',
    'txn_quickbooking_request_print.jasper',
    '/reports/transaction/txn_quickbooking_request_print.jasper',
    'labbit_primary',
    'select * from quickbookings where id = :quickbooking_id and lab_id = :lab_id;',
    'sp_txn_quickbooking_request_print',
    'Printable quickbooking request copy.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"quickbooking_id","label":"Quickbooking","type":"uuid","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_sample_pickup_slip',
    'Sample Pickup Slip',
    'Sample Pickup Slip',
    'transaction_print',
    'jasper',
    'TxnSamplePickupSlip',
    'txn_sample_pickup_slip.jasper',
    '/reports/transaction/txn_sample_pickup_slip.jasper',
    'labbit_primary',
    'select sp.*, cc.name as centre_name from sample_pickups sp left join collection_centre cc on cc.id = sp.collection_centre_id where sp.id = :pickup_id and sp.lab_id = :lab_id;',
    'sp_txn_sample_pickup_slip',
    'Pickup slip for logistics and receiving desk.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"pickup_id","label":"Pickup","type":"uuid","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_collection_centre_manifest_print',
    'Collection Centre Manifest Print',
    'Centre Manifest',
    'transaction_print',
    'jasper',
    'TxnCollectionCentreManifestPrint',
    'txn_collection_centre_manifest_print.jasper',
    '/reports/transaction/txn_collection_centre_manifest_print.jasper',
    'labbit_primary',
    'select sp.*, cc.name as centre_name from sample_pickups sp left join collection_centre cc on cc.id = sp.collection_centre_id where sp.lab_id = :lab_id and sp.collection_centre_id = :collection_centre_id and date(sp.created_at) = :for_date order by sp.created_at;',
    'sp_txn_collection_centre_manifest_print',
    'Daily manifest by collection centre.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"collection_centre_id","label":"Collection Centre","type":"uuid","required":true,"control":"select"},{"key":"for_date","label":"Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  ),
  (
    'txn_report_dispatch_receipt',
    'Report Dispatch Receipt',
    'Report Dispatch Receipt',
    'transaction_print',
    'jasper',
    'TxnReportDispatchReceipt',
    'txn_report_dispatch_receipt.jasper',
    '/reports/transaction/txn_report_dispatch_receipt.jasper',
    'labbit_primary',
    'select * from report_dispatch_logs where id = :dispatch_log_id;',
    'sp_txn_report_dispatch_receipt',
    'Printable receipt of report dispatch action.',
    '[{"key":"dispatch_log_id","label":"Dispatch Log","type":"bigint","required":true,"control":"lookup"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":false}'::jsonb,
    true,
    1
  ),
  (
    'txn_whatsapp_conversation_print',
    'WhatsApp Conversation Print',
    'WhatsApp Conversation Transcript',
    'transaction_print',
    'jasper',
    'TxnWhatsappConversationPrint',
    'txn_whatsapp_conversation_print.jasper',
    '/reports/transaction/txn_whatsapp_conversation_print.jasper',
    'labbit_primary',
    'select created_at, direction, message_type, body, media_url from whatsapp_messages where lab_id = :lab_id and phone = :phone and date(created_at) between :from_date and :to_date order by created_at;',
    'sp_txn_whatsapp_conversation_print',
    'Transcript print for WhatsApp support and legal review.',
    '[{"key":"lab_id","label":"Lab","type":"uuid","required":true,"control":"select"},{"key":"phone","label":"Phone","type":"text","required":true,"control":"text"},{"key":"from_date","label":"From Date","type":"date","required":true,"control":"date"},{"key":"to_date","label":"To Date","type":"date","required":true,"control":"date"}]'::jsonb,
    '{"pdf":true,"xlsx":false,"csv":false}'::jsonb,
    '{"enforce_lab_scope":true,"lab_param_key":"lab_id"}'::jsonb,
    true,
    1
  )
on conflict (report_key) do update set
  report_name = excluded.report_name,
  report_title = excluded.report_title,
  report_type = excluded.report_type,
  engine = excluded.engine,
  jasper_report_name = excluded.jasper_report_name,
  jasper_file_name = excluded.jasper_file_name,
  jasper_path = excluded.jasper_path,
  data_source_key = excluded.data_source_key,
  query_template = excluded.query_template,
  procedure_name = excluded.procedure_name,
  description = excluded.description,
  param_schema = excluded.param_schema,
  export_options = excluded.export_options,
  scope_rules = excluded.scope_rules,
  is_active = excluded.is_active,
  updated_at = now();
