-- report_half_days: employee-seeded calendar dates where the lab shuts
-- early (festival half-days etc.), read by py_utils' report-sender worker
-- to run the same-day partial-report cutoff earlier (see
-- worker.partial_send_cutoff_overrides.half_day in report_sender.json) --
-- same reasoning as the existing Sunday-earlier-cutoff override, just for
-- dates staff seed ahead of time instead of a fixed weekday.
create table if not exists public.report_half_days (
  id bigint generated by default as identity primary key,
  half_date date not null unique,
  note text null,
  created_by uuid null,
  created_by_name text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_report_half_days_date
  on public.report_half_days (half_date);
